In [1]:
%load_ext autoreload
%autoreload 2
import os
if 'Notebooks' in os.getcwd():
    project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
    os.chdir(project_root)

from Modules.DataLoaderModule import DataLoader
import numpy as np

In [2]:
loader = DataLoader()
X,Y = loader.load_data_from_folder_as_png('data')
ok = 0
duze = 0
for i in range(len(X)):
    if np.shape(X[i]) == (161,640):
        duze +=1
    else:
        ok+=1
print(duze)
print(ok)

129
2862


In [3]:
loader.load_single_photo('E:/OneDrive/Pulpit/BSc-thesis/data/train/train/Normal/9100442L.png')

array([[113, 115, 121, ...,  40,  36,  32],
       [113, 115, 119, ...,  39,  36,  35],
       [113, 112, 118, ...,  38,  33,  33],
       ...,
       [ 55,  53,  56, ..., 136, 126, 116],
       [ 56,  56,  59, ..., 134, 123, 116],
       [ 56,  58,  58, ..., 134, 124, 121]], dtype=uint8)

In [5]:
loader.load_single_photo(r"E:\OneDrive\Pulpit\BSc-thesis\data\train\train\Normal\9457863R.png")

array([[ 77,  78,  79, ...,  92,  92,  91],
       [ 77,  78,  78, ...,  92,  91,  90],
       [ 77,  77,  76, ...,  91,  92,  92],
       ...,
       [102, 100,  97, ...,  57,  55,  57],
       [102, 101,  98, ...,  58,  56,  55],
       [ 99, 104, 105, ...,  56,  55,  56]], dtype=uint8)

In [23]:
loader.save_data_as_array('test', X, Y)

File saved


In [32]:
X,Y = loader.load_data_as_array('test')

In [33]:
print(X)
print(Y)

[array([[116, 114, 115, ..., 123, 125, 122],
        [116, 113, 113, ..., 123, 126, 125],
        [112, 111, 110, ..., 124, 121, 124],
        ...,
        [111, 110, 114, ...,  75,  76,  76],
        [110, 110, 114, ...,  77,  75,  77],
        [109, 107, 114, ...,  75,  73,  76]], dtype=uint8)
 array([[141, 143, 142, ...,  90,  88,  86],
        [142, 142, 142, ...,  91,  90,  87],
        [139, 140, 140, ...,  92,  90,  87],
        ...,
        [ 37,  41,  46, ..., 177, 175, 163],
        [ 41,  41,  45, ..., 175, 171, 161],
        [ 39,  41,  45, ..., 172, 166, 154]], dtype=uint8)
 array([[113, 115, 121, ...,  40,  36,  32],
        [113, 115, 119, ...,  39,  36,  35],
        [113, 112, 118, ...,  38,  33,  33],
        ...,
        [ 55,  53,  56, ..., 136, 126, 116],
        [ 56,  56,  59, ..., 134, 123, 116],
        [ 56,  58,  58, ..., 134, 124, 121]], dtype=uint8) ...
 array([[84, 84, 84, ..., 66, 66, 66],
        [84, 84, 84, ..., 66, 66, 66],
        [84, 84, 84, ..., 6