In [1]:
%load_ext autoreload
%autoreload 2
import os
if 'Notebooks' in os.getcwd():
    project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
    os.chdir(project_root)

from Modules.DataLoaderModule import DataLoader
from Modules.PreprocessingModule import Preprocessor
from Modules.StatisticsModule import Statistics
import numpy as np
import cv2

In [149]:
loader = DataLoader()
X,Y = loader.load_data_from_folder_as_png('data')
ok = 0
duze = 0
for i in range(len(X)):
    if np.shape(X[i]) == (161,640):
        duze +=1
    else:
        ok+=1
print(duze)
print(ok)

129
2862


In [3]:
loader.load_single_photo('E:/OneDrive/Pulpit/BSc-thesis/data/train/train/Normal/9100442L.png')

array([[113, 115, 121, ...,  40,  36,  32],
       [113, 115, 119, ...,  39,  36,  35],
       [113, 112, 118, ...,  38,  33,  33],
       ...,
       [ 55,  53,  56, ..., 136, 126, 116],
       [ 56,  56,  59, ..., 134, 123, 116],
       [ 56,  58,  58, ..., 134, 124, 121]], dtype=uint8)

In [154]:
loader.load_single_photo(r"E:\OneDrive\Pulpit\BSc-thesis\data\train\train\Normal\9457863R.png")

[array([[ 77,  78,  79, ...,  92,  92,  91],
        [ 77,  78,  78, ...,  92,  91,  90],
        [ 77,  77,  76, ...,  91,  92,  92],
        ...,
        [102, 100,  97, ...,  57,  55,  57],
        [102, 101,  98, ...,  58,  56,  55],
        [ 99, 104, 105, ...,  56,  55,  56]], dtype=uint8)]

In [23]:
loader.save_data_as_array('test', X, Y)

File saved


In [32]:
X,Y = loader.load_data_as_array('test')

In [33]:
print(X)
print(Y)

[array([[116, 114, 115, ..., 123, 125, 122],
        [116, 113, 113, ..., 123, 126, 125],
        [112, 111, 110, ..., 124, 121, 124],
        ...,
        [111, 110, 114, ...,  75,  76,  76],
        [110, 110, 114, ...,  77,  75,  77],
        [109, 107, 114, ...,  75,  73,  76]], dtype=uint8)
 array([[141, 143, 142, ...,  90,  88,  86],
        [142, 142, 142, ...,  91,  90,  87],
        [139, 140, 140, ...,  92,  90,  87],
        ...,
        [ 37,  41,  46, ..., 177, 175, 163],
        [ 41,  41,  45, ..., 175, 171, 161],
        [ 39,  41,  45, ..., 172, 166, 154]], dtype=uint8)
 array([[113, 115, 121, ...,  40,  36,  32],
        [113, 115, 119, ...,  39,  36,  35],
        [113, 112, 118, ...,  38,  33,  33],
        ...,
        [ 55,  53,  56, ..., 136, 126, 116],
        [ 56,  56,  59, ..., 134, 123, 116],
        [ 56,  58,  58, ..., 134, 124, 121]], dtype=uint8) ...
 array([[84, 84, 84, ..., 66, 66, 66],
        [84, 84, 84, ..., 66, 66, 66],
        [84, 84, 84, ..., 6

In [7]:
Preprocessor.normalize_data(X)

array([array([[0.45490196, 0.44705882, 0.45098039, ..., 0.48235294, 0.49019608,
               0.47843137],
              [0.45490196, 0.44313725, 0.44313725, ..., 0.48235294, 0.49411765,
               0.49019608],
              [0.43921569, 0.43529412, 0.43137255, ..., 0.48627451, 0.4745098 ,
               0.48627451],
              ...,
              [0.43529412, 0.43137255, 0.44705882, ..., 0.29411765, 0.29803922,
               0.29803922],
              [0.43137255, 0.43137255, 0.44705882, ..., 0.30196078, 0.29411765,
               0.30196078],
              [0.42745098, 0.41960784, 0.44705882, ..., 0.29411765, 0.28627451,
               0.29803922]])                                                   ,
       array([[0.55294118, 0.56078431, 0.55686275, ..., 0.35294118, 0.34509804,
               0.3372549 ],
              [0.55686275, 0.55686275, 0.55686275, ..., 0.35686275, 0.35294118,
               0.34117647],
              [0.54509804, 0.54901961, 0.54901961, ..., 0.360784

In [13]:
data = Preprocessor.split_data(X, Y)

In [14]:
for el in data:
    print(len(el))

2033
509
449
2033
509
449


In [41]:
for el in X:
    if np.shape(el) == (161, 640):
        d = cv2.resize(el, (224,224))
        c = el
        break
print(d)

[[33 39 41 ... 51 46 37]
 [32 39 41 ... 50 45 37]
 [30 39 41 ... 51 43 37]
 ...
 [64 68 70 ...  0  0  0]
 [64 69 70 ...  0  0  0]
 [65 69 71 ...  0  0  0]]


In [43]:
cv2.imshow('image',c)
cv2.waitKey(0)
cv2.imshow('image',d)
cv2.waitKey(0)

-1

In [28]:
np.shape(d)

(224, 224)

In [44]:
left_part =c[:, :320]
right_part = c[:, 320:]

In [ ]:
cv2.imshow('image',c)
cv2.waitKey(0)
cv2.imshow('image',left_part)
cv2.waitKey(0)
cv2.imshow('image',right_part)
cv2.waitKey(0)

-1

In [69]:
indexy = [i for i, v in enumerate(X) if np.shape(v) == (161,640)]

In [70]:
len(indexy)

129

In [73]:
wykluczone = [i for i in range(len(X)) if i not in indexy]

In [75]:
len(wykluczone)

2862

In [80]:
x = [1,1,0,1,0,1,1,0,0]
np.repeat(x,2)

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0])

In [107]:
x, y = Preprocessor.split_wide_photos(X,Y)

In [108]:
X_res = Preprocessor.resize_photos(x)

In [111]:
cv2.imshow('image',X_res[2011])
cv2.waitKey(0)

-1

In [113]:
len(X_res)
len(y)

3120

In [ ]:
test = X_res[0]

-1

In [123]:
test_fliped = cv2.flip(test,1)

In [126]:
cv2.imshow('image',test)
cv2.waitKey(0)
cv2.imshow('image',test_fliped)
cv2.waitKey(0)

-1

In [137]:
X_flip, Y_flip = Preprocessor.flip_photos(X_res,y)

In [139]:
cv2.imshow('image',X_flip[0])
cv2.waitKey(0)
cv2.imshow('image',X_flip[1])
cv2.waitKey(0)

-1

In [131]:
cos = np.repeat(x,2)

In [150]:
X_train, X_test, X_val, Y_train, Y_test, Y_val = Preprocessor.split_data(X,Y)

In [2]:
Y = np.array([0,0,1,1,1,1,1,0,1,1])
Y_pred = np.array([0,1,1,0,1,1,0,0,1,1])
Statistics.accuracy(Y, Y_pred)

0.7

In [9]:
Statistics.f1_score(Y, Y_pred)

0.7692307692307693

In [12]:
Statistics.preccision(Y, Y_pred)

0.8333333333333334

In [14]:
Statistics.recall(Y, Y_pred)

0.7142857142857143

In [16]:
Statistics.auc(Y,Y_pred)

ValueError: x is neither increasing nor decreasing : [0 0 1 1 1 1 1 0 1 1].